device: "mps"
seed: 20
embed_size: 1024
temp: 0.07
resume: false
embed_regularization: true

perceptual_args:
  feature_dim: 512  # opsiyonel: otomatik hesaplanıyor

data_args:
  train_pkl: "perceptual_model/outputs/train_perceptual_features_proper.pkl"
  val_pkl: "perceptual_model/outputs/validation_perceptual_features_proper.pkl"
  test_pkl: "perceptual_model/outputs/test_perceptual_features_proper.pkl"
  batch_size: 32
  num_workers: 8

text_encoder_args:
  type: 'bert-base-uncased'
  freeze: false

optim_args:
  lr: !!float 5e-5
  warmup_steps: 0
  optimizer_name: "adam"
  betas: [0.9, 0.999]
  eps: !!float 1e-8
  momentum: 0.9
  warmup_epochs: 2

training:
  epochs: 15
  clip_grad: 2
  dropout: 0.2

dist_args:
  world_size: 1
  dist_url: "env://"

n_jobs: 8